### ISSUE TITLE
Scrambled Russian Translation Encoding

### ISSUE THREAD

**Issue by Nekuromu** [Goldbar97/mods#17]
![image](https://github.com/Goldbar97/mods/assets/30809120/3e4ad320-6e9e-4c9b-81ea-cb0fc8618463)

![image](https://github.com/Goldbar97/mods/assets/30809120/fed3fcf3-6be1-4dc3-9cec-87245bc0afdd) Mokryy Ananas
> "Seems like the Russian translation has been broken after the recent update, with weird symbols instead of the correct translation for items and crafting recipes."

![image](https://github.com/Goldbar97/mods/assets/30809120/88e4a425-0496-4eb2-9944-398b4c0ff438) YolingArtist
> "You can easily fix the Cyrillic alphabet yourself. In the folder with the mod, rewrite 3 files with translation yourself (in the pinned discussion there is ready-made text for the largest file, the rest can be rewritten manually or use converters on the Internet)."

Seems like we have some issues with the russian encoding/translation. I went all the way back to the inital commit even then it seems the encoding is a bit funky. There is one file that seems to be correctly being encoded: Recipes_RU.txt; (The others when put into the same encoding turn into gibberish)

so somehow we ended up scrambling the encoding somewhere along the way possibly?

Windows 1252 encoding is what seemingly works on Recipes_RU.txt so we may need to re-translate both ItemName_RU.txt & IG_UI_RU.txt for that, But when researching [Windows 1252](https://en.wikipedia.org/wiki/Windows-1251) it may be best to use UTF-8 as per this paragraph from the linked article:

> "Unicode (e.g. UTF-8) is preferred to Windows-1251 or other Cyrillic encodings in modern applications, especially on the Internet, making UTF-8 the dominant encoding for web pages. (For further discussion of Unicode's complete coverage, of 436 Cyrillic letters/code points, including for Old Cyrillic, and how single-byte character encodings, such as Windows-1251 and KOI8-R, cannot provide this, see Cyrillic script in Unicode.)"

**Comment by Goldbar97** [comment]
Ok, I checked the game's translation file to see what encoding it uses. It's Windows-1251 so I encoded our translation files also. I just committed and see how it works.
