### ISSUE TITLE
Adding Comic Book & Crossword/Wordsearch Magazine Stacks

### ISSUE THREAD

**Issue by Nekuromu** [Goldbar97/mods#4]
![image](https://github.com/Goldbar97/mods/assets/30809120/645ca954-bfcd-4e6b-b7b6-7d6fa746d0ef)

**Comment by Goldbar97** [comment]
I will gather the scripts code and materialize it

**Comment by Goldbar97** [comment]
I just pushed commit to the main. I'm considering for making the books interchangable.

**Comment by Nekuromu** [comment]
Added to the mod as of commit a06d9dd!
